apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pubsub
spec:
  template:
    metadata:
      labels:
        app: pubsub
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub
      containers:
      - name: subscriber
        image: runseb/listengcs
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
